services:
  - type: web
    name: kakao-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false 