services:
  - type: web
    name: kakao-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: PORT
        value: 10000 